//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.Web07.GD.ndquang.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.Web07.GD.ndquang.Common.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên đã tồn tại.
        /// </summary>
        public static string duplicateCode_expception {
            get {
                return ResourceManager.GetString("duplicateCode_expception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không hợp lệ.
        /// </summary>
        public static string email_expception {
            get {
                return ResourceManager.GetString("email_expception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số hiệu cán bộ không được phép để trống.
        /// </summary>
        public static string empCodeRequired_expception {
            get {
                return ResourceManager.GetString("empCodeRequired_expception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên không được phép để trống.
        /// </summary>
        public static string empNameRequired_expception {
            get {
                return ResourceManager.GetString("empNameRequired_expception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra. Vui lòng liên hệ MISA!.
        /// </summary>
        public static string error_expception {
            get {
                return ResourceManager.GetString("error_expception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thao tác không thành công.
        /// </summary>
        public static string failedOperation {
            get {
                return ResourceManager.GetString("failedOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày nghỉ việc không được lớn hơn ngày hiện tại.
        /// </summary>
        public static string quitDate_expception {
            get {
                return ResourceManager.GetString("quitDate_expception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại không đủ độ dài.
        /// </summary>
        public static string telNumber_expception {
            get {
                return ResourceManager.GetString("telNumber_expception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi validate dữ liệu không đúng format.
        /// </summary>
        public static string validate_expception {
            get {
                return ResourceManager.GetString("validate_expception", resourceCulture);
            }
        }
    }
}
